server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.80.128:3306/metrics
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  redis:
    host: 192.168.80.128
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s

mybatis-plus:
  type-aliases-package: com.hw.server.domain     # 别名扫描包

logging:
  level:
    com.hw.server: debug